package statutesws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-08-27T08:51:52.802-07:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://statutesws/", name = "StatutesWS")
@XmlSeeAlso({ObjectFactory.class, statutes.ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface StatutesWS {

    @WebMethod
    @WebResult(name = "responseArray", targetNamespace = "http://statutesws/", partName = "responseArray")
    public ResponseArray findStatutes(
        @WebParam(partName = "keys", name = "keys")
        StatuteKeyArray keys
    );

    @WebMethod
    @WebResult(name = "statutesTitlesArray", targetNamespace = "http://statutesws/", partName = "statutesTitlesArray")
    public StatutesTitlesArray getStatutesTitles();
}
